### ISSUE TITLE
Cannot auth to google drive

### ISSUE THREAD

**Issue by cactushydrocodone** [pstaender/csup#2]
When i accept the o auth request, i get redirected to localhost and it doesnt Displays any code.

**Comment by pstaender** [comment]
Hi,

please ensure that you configure the settings with the correct redirect URL:

An example `~/.csup` file (can be genearted with csup setup):

```yaml
clientID: '…apps.googleusercontent.com'
clientSecret: '…'
redirectURL: 'https://yourserver.com/csup/auth.php'
```

Setup the ClientID, ClientSecret and redirectURL in https://developers.google.com/drive/v3/web/enable-sdk (here an example of my settings):

 
![screen shot 2016-12-10 at 14 33 03](https://cloud.githubusercontent.com/assets/140571/21073712/d27488b6-bee6-11e6-9c45-8c0687b4b62b.png)

Finally you'll need to enter the code that is attached to the redirect url, e.g.: `https://yourserver.com/csup/auth.php?code=2/abcdefehdejkl21uasdas-DS66DASBNM#` would follow to be the code for csup: `2/abcdefehdejkl21uasdas-DS66DASBNM`
